### ISSUE TITLE
Cant seem to do variable replacement for "like" queries

### ISSUE THREAD

**Issue by avallark** [kumarshantanu/asphalt#10]
```sql
select x from b where name like '$name-this%'; 
```
is not getting substituted correctly.  The variables are correctly populated, but the final query isnt getting executed properly.

A debugging guide would be super helpful :)

**Comment by avallark** [comment]
Problem was with putting the variable inside single-quotes. That isnt necessary. Once I removed that, things worked fine with the following:
```sql
select x from b where name like concat($name-this,'%'); 
```
The above concat is important as this will add the much needed % at the end of the variable. One awesome feature of using like is that it does case insensitive searches by default!

**Comment by kumarshantanu** [comment]
👍
